spring: 
 profiles: 
  active: 
  - dev
  
---
server: 
 port: 8001

mybatis:
 config-location: classpath:mybatis/mybatis-config.xml
 type-aliases-package: com.springcloud.entity
 mapper-locations:  
 - classpath:mybatis/mapper/*.xml
 
spring: 
 profiles: dev
 application: 
  name: microservice-config-emp-client
 datasource: 
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://localhost:3306/db_myschool
  username: root
  password: root
  dbcp2: 
   min-idle: 5
   initial-size: 5
   max-total: 5
   max-wait-millis: 200 
   
eureka:
 #注册到指定地址的eureka的服务器
 client: 
  service-url: 
   defaultZone: http://eureka7001.com:7001/eureka
 #自己定义一个别名
 instance: 
  instance-id: microservicecloud-emp-config8001
  #访问路径可以显示IP
  prefer-ip-address: true

info: 
 app: 
  name: cdedu-microservicecloud
 company: 
  name: www.cdedu.com
 build: 
  artifactId: $project.artifactId$
  version: $project.version$
  
---
server: 
 port: 8001

mybatis:
 config-location: classpath:mybatis/mybatis-config.xml
 type-aliases-package: com.cdedu.springcloud.entity
 mapper-locations:  
 - classpath:mybatis/mapper/*.xml
 
spring: 
 profiles: test
 application: 
  name: microservice-config-emp-client
 datasource: 
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://localhost:3306/db_myschool01
  username: root
  password: root
  dbcp2: 
   min-idle: 5
   initial-size: 5
   max-total: 5
   max-wait-millis: 200 
   
eureka:
 #注册到指定地址的eureka的服务器
 client: 
  service-url: 
   defaultZone: http://eureka7001.com:7001/eureka
 #自己定义一个别名
 instance: 
  instance-id: microservicecloud-emp-config8001
  #访问路径可以显示IP
  prefer-ip-address: true

info: 
 app: 
  name: cdedu-microservicecloud
 company: 
  name: www.cdedu.com
 build: 
  artifactId: $project.artifactId$
  version: $project.version$
